name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run tests
        run: pytest -q

  action-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [docker, composite]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: KubePolicy (pass case) - ${{ matrix.variant }}
        if: matrix.variant == 'docker'
        uses: ./
        env:
          KPB_FILE_GLOBS: samples/good/*.yaml
        with:
          severity_threshold: error
          include_glob: "**/*.yml,**/*.yaml"
          exclude_glob: ""
          post_pr_comment: false
      - name: KubePolicy (pass case) - ${{ matrix.variant }}
        if: matrix.variant == 'composite'
        uses: ./composite
        env:
          KPB_FILE_GLOBS: samples/good/*.yaml
        with:
          severity_threshold: error
          include_glob: "**/*.yml,**/*.yaml"
          exclude_glob: ""
          post_pr_comment: false
      - name: KubePolicy (fail case, continue) - ${{ matrix.variant }}
        if: matrix.variant == 'docker'
        continue-on-error: true
        uses: ./
        env:
          KPB_FILE_GLOBS: samples/bad/*.yaml
        with:
          severity_threshold: error
          include_glob: "**/*.yml,**/*.yaml"
          exclude_glob: ""
          post_pr_comment: false
      - name: KubePolicy (fail case, continue) - ${{ matrix.variant }}
        if: matrix.variant == 'composite'
        continue-on-error: true
        uses: ./composite
        env:
          KPB_FILE_GLOBS: samples/bad/*.yaml
        with:
          severity_threshold: error
          include_glob: "**/*.yml,**/*.yaml"
          exclude_glob: ""
          post_pr_comment: false

